DROP TABLE IF EXISTS Brands CASCADE;

DROP TABLE IF EXISTS Categories CASCADE;

DROP TABLE IF EXISTS Products CASCADE;

DROP TABLE IF EXISTS Images CASCADE;

DROP TABLE IF EXISTS PreviewImages CASCADE;

DROP TABLE IF EXISTS Hijabs CASCADE;