-- insert value 
INSERT INTO Brands(BrandName, BrandUrl)
VALUES ('Nea', 'https://n-e-a.co.uk/');

INSERT INTO Categories(CategoryName)
VALUES ('Hijab');

INSERT INTO Products(ProductName, PriceInEuros, ProductUrl, Gender, ProductDetail, MainImageUrl, BrandName, CategoryName)
VALUES 
    ('Enara', 20.00, 'https://n-e-a.co.uk/collections/lur/products/luna-1', 'F', 'Enara means Swallow bird in Basque. An opaque black, a very special shade of black that makes Enara feel very luxurious. Made from the softest jersey material. Looks beautiful in any skin color. Its thickness makes it especially suitable for the fall-winter seasons, however, it can be worn in summer if styled appropriately. It is very stretchy and stylish, can be worn as a turban and its weight allows you to let your creativity flow with the way you want to wear it. Enara is all about freedom of expression, not your regular jersey hijab. Your love for Enara is guaranteed as it is made with the intention of making you feel confident and content with who you are, like the birds that fly so majestically over our heads without any pretense, just being free.\nWe will donate £1 from the total price of each hijab bought from our Lur collection to a cause or charity that will be picked collectively alongside our costumers in our social media channels.\nOur limited edition Jersey scarves are light, medium to heavyweight, made of natural jersey fabric. With a luxuriously soft touch, they can be styled in various ways. Made sustainably by recycled fabrics and upcycled dead stock from premium Italian fabric houses. Manufactured and made in the UK by women-owned factories that have been regulated and assessed to ensure ethical living and working conditions. Nea is made to last.\nTextile: Sustainably sourced jersey, upcycled.\nDimension: 70\"x 30\"\nContour: Long Rectangle\nThickness: heavy.\nTexture: Smooth\nBreathable, heavyweight fabric.\nPerfect for fall-winter season, quick styling and special occasions.\nNo underscarf or pins required.\nQuality guarantee: 30-day return policy\nOpacity Non-Sheer.', 'https://cdn.shopify.com/s/files/1/0262/8799/6976/products/enara_1024x1024@2x.jpg?v=1582627343','Nea', 'Hijab'),
    ('Luna', 20.00, 'https://n-e-a.co.uk/collections/lur/products/luna', 'F', 'Luna means moon in Spanish. A silver shine color that emulates the moonlight, a glamorous and luxurious hijab made of the softest jersey material. Looks beautiful in any skin color and can be worn in any season. Luna is mediumweight and ideal to add a touch of glamour to your everyday outfit or for a special occasion. Your love for Luna is guaranteed as it is made with the intention of making you look beautiful in the most effortless way every time you wear it, like the moonlight in a clear summer night.\nWe will donate £1 from the total price of each hijab bought from our Lur collection to a cause or charity that will be picked collectively alongside our costumers in our social media channels.\nOur limited edition Jersey scarves are light, medium to heavyweight, made of natural jersey fabric. With a luxuriously soft touch, they can be styled in various ways. Made sustainably by recycled fabrics and upcycled dead stock from premium Italian fabric houses. Manufactured and made in the UK by women-owned factories that have been regulated and assessed to ensure ethical living and working conditions. Nea is made to last.\nTextile: Sustainably sourced jersey, upcycled.\nDimension: 70\"x 30\"\nContour: Long Rectangle\nThickness: Light.\nTexture: Smooth\nBreathable, mediumweight fabric.\nPerfect for any season, quick styling and special occasions.\nNo underscarf or pins required.\nQuality guarantee: 30-day return policy\nOpacity Non-Sheer.', 'https://cdn.shopify.com/s/files/1/0262/8799/6976/products/image_1024x1024@2x.jpg?v=1581609991','Nea', 'Hijab'),
    ('Safaa', 20.00, 'https://n-e-a.co.uk/collections/lur/products/safaa', 'F', 'Safaa means pure in Arabic. A perfect shade of white with a soft warm undertone that makes Safaa look very luxurious. Made from the softest jersey material. Looks beautiful in any skin color. Its thickness makes it especially suitable for the fall-winter seasons, however, it can be worn in summer if styled for it. It is very stretchy and stylish, can be worn as a turban and its weight allows you to let your creativity flow with the way you want to wear it. Safaa is all about elegance and modesty, not your regular white jersey hijab. Your love for Safaa is guaranteed as it is made with the intention of making you feel peaceful and empowered in your choice to cover. Pure like the mind and heart when they remember Allah and their purpose in this world.\nWe will donate £1 from the total price of each hijab bought from our Lur collection to a cause or charity that will be picked collectively alongside our costumers in our social media channels.\nOur limited edition Jersey scarves are light, medium to heavyweight, made of natural jersey fabric. With a luxuriously soft touch, they can be styled in various ways. Made sustainably by recycled fabrics and upcycled dead stock from premium Italian fabric houses. Manufactured and made in the UK by women-owned factories that have been regulated and assessed to ensure ethical living and working conditions. Nea is made to last.\nTextile: Sustainably sourced jersey, upcycled.\nDimension: 70\"x 30\"\nContour: Long Rectangle\nThickness: heavy.\nTexture: Smooth\nBreathable, heavyweight fabric.\nPerfect for fall-winter season, quick styling and special occasions.\nNo underscarf or pins required.\nQuality guarantee: 30-day return policy\nOpacity Non-Sheer.', 'https://cdn.shopify.com/s/files/1/0262/8799/6976/products/image_2b41467f-35bb-4f20-86d3-9ebcfaef1219_1024x1024@2x.jpg?v=1578402518','Nea', 'Hijab'),
    ('Bunga', 20.00, 'https://n-e-a.co.uk/collections/lur/products/bunga', 'F', 'Bunga means flower in Malay. A reddish maroon color that flatters any skin shade and any season. Bunga is lightweight and extremely versatile, your love for Bunga is guaranteed as it is made with the intention of making you happy every time you wear it, as a flower would.\nWe will donate £1 from the total price of each hijab bought from our Lur collection to a cause or charity that will be picked collectively alongside our costumers in our social media channels.\nOur limited edition Jersey scarves are light, medium to heavyweight, made of natural jersey fabric. With a luxuriously soft touch, they can be styled in various ways. Made sustainably by recycled fabrics and upcycled dead stock from premium Italian fabric houses. Manufactured and made in the UK by women-owned factories that have been regulated and assessed to ensure ethical living and working conditions. They area made to last.\nTextile: Sustainably sourced jersey, upcycled.\nDimension: 70\"x 30\"\nContour: Long Rectangle\nThickness: Light.\nTexture: Smooth\nBreathable, light-weight fabric, stretchy.\nPerfect for any season, quick styling and working out.\nNo underscarf or pins required\nQuality guarantee: 30-day return policy\nSheer-Medium.', 'https://cdn.shopify.com/s/files/1/0262/8799/6976/products/image_ef073d31-af3a-400f-9d5f-3f2d6c576a69_1024x1024@2x.jpg?v=1581596267', 'Nea', 'Hijab');

-- INSERT INTO Hijabs(ProductId, ProductName,PriceInEuros,ProductDescription,DonationMessage,TextileDescription,TextileType,Dimensions,Contour,Thickness,Texture,Breathability,Seasonal,AccessoryRequired,QualityGuarantee,Opacity)
-- VALUES
--     (1, 'Enara',20.0,'Enara means Swallow bird in Basque. An opaque black, a very special shade of black that makes Enara feel very luxurious. Made from the softest jersey material. Looks beautiful in any skin color. Its thickness makes it especially suitable for the fall-winter seasons, however, it can be worn in summer if styled appropriately. It is very stretchy and stylish, can be worn as a turban and its weight allows you to let your creativity flow with the way you want to wear it. Enara is all about freedom of expression, not your regular jersey hijab. Your love for Enara is guaranteed as it is made with the intention of making you feel confident and content with who you are, like the birds that fly so majestically over our heads without any pretense, just being free.','We will donate 1 from the total price of each hijab bought from our Lur collection to a cause or charity that will be picked collectively alongside our costumers in our social media channels.','Our limited edition Jersey scarves are light, medium to heavyweight, made of natural jersey fabric. With a luxuriously soft touch, they can be styled in various ways. Made sustainably by recycled fabrics and upcycled dead stock from premium Italian fabric houses. Manufactured and made in the UK by women-owned factories that have been regulated and assessed to ensure ethical living and working conditions. Nea is made to last.','Sustainably sourced jersey, upcycled.','70""x 30""','Long Rectangle','heavy','Smooth','Breathable, heavyweight fabric.','Perfect for fall-winter season, quick styling and special occasions.','No underscarf or pins required.','Quality guarantee: 30-day return policy','Non-Sheer');

-- INSERT INTO Images(ImageUrl, ProductId)
-- VALUES
--     ('https://cdn.shopify.com/s/files/1/0262/8799/6976/products/enara_1024x1024@2x.jpg?v=1582627343','Enara');

-- INSERT INTO PreviewImages(PreviewImageUrl, ProductId)
-- VALUES
--     ('https://cdn.shopify.com/s/files/1/0262/8799/6976/products/enara_110x110@2x.jpg?v=1582627343','Enara'),
--     ('https://cdn.shopify.com/s/files/1/0262/8799/6976/products/image_8bdf4c09-dbae-4bbf-b1fa-f6210dcdd73b_110x110@2x.jpg?v=1582627343','Enara'),
--     ('https://cdn.shopify.com/s/files/1/0262/8799/6976/products/IMG_9291_110x110@2x.jpg?v=1582627343','Enara'),
--     ('https://cdn.shopify.com/s/files/1/0262/8799/6976/products/NEA-26_110x110@2x.jpg?v=1582627343','Enara'),
--     ('https://cdn.shopify.com/s/files/1/0262/8799/6976/products/image_ef6861b3-500e-473c-9d6f-6a30791a1834_110x110@2x.jpg?v=1582627343','Enara'),
--     ('https://cdn.shopify.com/s/files/1/0262/8799/6976/products/image_93fdeadf-c8d8-4373-b6c9-c9dbe941c347_110x110@2x.jpg?v=1582627343','Enara');

-- eb data
INSERT INTO Brands(BrandName, BrandUrl)
VALUES ('ElectricBazaar', 'https://www.electric-bazaar.com/heritage');

INSERT INTO Categories(CategoryName)
VALUES 
    ('Gharara'),
    ('Kimono'),
    ('Dress');

INSERT INTO Products(ProductName, PriceInEuros, ProductUrl, Gender, ProductDetail, MainImageUrl, BrandName, CategoryName)
VALUES
    ('Purple Crochet Kimono', 35.00, 'https://www.electric-bazaar.com/product-page/purple-crochet-kimono', 'F', 'Loose-Fit Sheer Open Kimono\nDelicate Purple Threadwork\nWide Drop Sleeves with Scallop Detail', 'https://static.wixstatic.com/media/78c8d2_43a491b82bb64bdabb358941850d9d1c~mv2_d_3717_5534_s_4_2.jpg/v1/fill/w_996,h_1496,al_c,q_85,usm_0.66_1.00_0.01/78c8d2_43a491b82bb64bdabb358941850d9d1c~mv2_d_3717_5534_s_4_2.jpg','ElectricBazarr', 'Kimono');

-- INSERT INTO Images(ImageUrl, ProductId)
-- VALUES
--     ('https://static.wixstatic.com/media/78c8d2_43a491b82bb64bdabb358941850d9d1c~mv2_d_3717_5534_s_4_2.jpg/v1/fill/w_996,h_1496,al_c,q_85,usm_0.66_1.00_0.01/78c8d2_43a491b82bb64bdabb358941850d9d1c~mv2_d_3717_5534_s_4_2.jpg');


--- using copy at psql

\copy products(productName,priceInEuros,productUrl,gender,productDetail,mainImageUrl,brandName,categoryName) from '/Users/limhyesu/meg/database/static_data/parsed_eb.csv' DELIMITER ',' CSV HEADER;